# Site settings
title: Ryan Conk's Portfolio
description: Ryan Conk's Full Stack Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ryan Conk
user_description: Dedicated Full Stack Software Engineer with a deep understanding of software development. Specialize in backend development, crafting the invisible infrastructure that powers cutting-edge applications. Expertise lies in designing and optimizing backend solutions, paired proficiency in database management and server technologies to create efficient and reliable systems that meet the demands of today's dynamic technology landscape. Driven by a passion for innovation and continuous improvement. Committed to building the backbone of digital solutions that drive success for businesses and elevate user experiences.
certificate: Certified SAFe 5 practitioner - Scaled Agile.
user_title: Full Stack Software Developer
email: ryangconk@gmail.com
twitter_username:
github_username: RyanGC93
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
