# Site settings
title: Ryan Conk's Portfolio
description: Ryan Conk's Full Stack Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ryan Conk
user_description: I'm a passionate software engineer who is motivated by continually growing my knowledge set. I have been interested in technology ever since I was 8 when I received my first PC Builder magazine and have been immersed ever since. In particular Im fascinated in technology role in solving problems. In my free time I enjoy challenging myself by creating innovative solutions to everyday problems.
certificate: Certified SAFe 5 practitioner - Scaled Agile.
user_title: Full Stack Software Developer
email: ryangconk@gmail.com
twitter_username:
github_username: RyanGC93
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
